[options]
; RebeccaGest Configuration File
; see https://www.rebeccagest.com/documentation/1.0/administration/install/deploy.html

; This is the password at the Odoo database manager screenpasswd_file =
; admin_passwd = admin

; Database settings
db_host = localhost
db_port = 5432
db_user = rebeccagest
db_password = rebeccagest
db_template = template1

; HTTP settings
http_port = 8069
http_interface = 127.0.0.1
http_enable = True

; Options for Proxy Mode
proxy_mode = False

; Addons
addons_path = addons

; Logs
log_level = info
log_handler = :INFO
log_db = False

; Limits
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120

; Email
smtp_server = mail.example.com
smtp_port = 25
smtp_ssl = False
smtp_user = False
smtp_password = False

; Security
secure_cookie = False
session_cookie = session_id
session_cookie_age = 7776000
session_cookie_httponly = True
session_cookie_samesite = Lax

; Development
dev_mode = False
